export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_SERVICE = 'FETCH_SERVICE';
export const FETCH_CLIENT_S = 'FETCH_CLIENT_S';
export const FETCH_PARTENAIRES = 'FETCH_PARTENAIRES';
export const FETCH_CONTACT = 'FETCH_CONTACT';
export const FETCH_CLIENTS = 'FETCH_CLIENTS';



